name: GettingSponsored
favicon: null
layout_spectrum: 0.03451951523311436
typography_spectrum: 0.7492496031336486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8184255505912006
  lightness: 0.205058463383466
  saturation: 0.06312588416039944
  rhythmicContrast: 0.551464622374624
purpose: []
